package ecom.domain;

import static ecom.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CriseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAllPropertiesEquals(Crise expected, Crise actual) {
        assertCriseAutoGeneratedPropertiesEquals(expected, actual);
        assertCriseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAllUpdatablePropertiesEquals(Crise expected, Crise actual) {
        assertCriseUpdatableFieldsEquals(expected, actual);
        assertCriseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAutoGeneratedPropertiesEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseUpdatableFieldsEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getNature()).as("check nature").isEqualTo(expected.getNature()))
            .satisfies(a ->
                assertThat(a.getDateDebut())
                    .as("check dateDebut")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDateDebut())
            )
            .satisfies(a ->
                assertThat(a.getDateFin()).as("check dateFin").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getDateFin())
            )
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseUpdatableRelationshipsEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise relationships")
            .satisfies(a -> assertThat(a.getSinistres()).as("check sinistres").isEqualTo(expected.getSinistres()));
    }
}
