package ecom.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DemandeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeAllPropertiesEquals(Demande expected, Demande actual) {
        assertDemandeAutoGeneratedPropertiesEquals(expected, actual);
        assertDemandeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeAllUpdatablePropertiesEquals(Demande expected, Demande actual) {
        assertDemandeUpdatableFieldsEquals(expected, actual);
        assertDemandeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeAutoGeneratedPropertiesEquals(Demande expected, Demande actual) {
        assertThat(actual)
            .as("Verify Demande auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeUpdatableFieldsEquals(Demande expected, Demande actual) {
        assertThat(actual)
            .as("Verify Demande relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTypeBesoin()).as("check typeBesoin").isEqualTo(expected.getTypeBesoin()))
            .satisfies(a -> assertThat(a.getGeolocalisation()).as("check geolocalisation").isEqualTo(expected.getGeolocalisation()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getIsArchived()).as("check isArchived").isEqualTo(expected.getIsArchived()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandeUpdatableRelationshipsEquals(Demande expected, Demande actual) {
        assertThat(actual)
            .as("Verify Demande relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()))
            .satisfies(a -> assertThat(a.getCrise()).as("check crise").isEqualTo(expected.getCrise()));
    }
}
